#!/bin/bash
#PBS -P q95
#PBS -q gpuvolta
#PBS -l walltime=48:00:00
#PBS -l mem=96GB
#PBS -l jobfs=16000MB
#PBS -l ngpus=1
#PBS -l ncpus=12
#PBS -l other=mpi:hyperthread
#PBS -l wd
#PBS -r y
#PBS -l storage=scratch/q95+gdata/q95

## General-purpose resubmit script for GROMACS jobs on gadi

## this runs jobs in four hour blocks with checkpinting and resubmission, 
## edit $GMXMDRUN to vary the runtime
## nsteps is set in the mdp
## Starting structure, .top, .ndx and .mdp should have the same name as the
## script, and all be in the same folder. Output will also have 
## the same name.
## Eg:  if script name is GlyT2_POPC_CHOL_r1, mdp is GlyT2_POPC_CHOL_r1.mdp
##
## IMPORTANT: SCRIPT NAME SHOULD NOT END WITH .sh

echo "CLUSTERID=GADI-gpuvolta" # print which cluster was used, so if a system is run on multiple systems I can separate the log files for benchmarking

module list
module load openmpi/4.1.5
module load gromacs/2024.3-gpuvolta

export OMP_NUM_THREADS=2
export OMP_PLACES=cores
export OMP_PROC_BIND=close

GMX='mpirun -np 6 gmx_mpi'
GMXMDRUN='mpirun -np 6 gmx_mpi mdrun -maxh 47.5'


# Define error function so we can see the error code given when something
# important crashes
errexit ()
{
    errstat=$?
    if [ $errstat != 0 ]; then
        # A brief nap so PBS kills us in normal termination
        # Prefer to be killed by PBS if PBS detected some resource
        # excess
        sleep 5
        echo "Job returned error status $errstat - stopping job sequence $PBS_JOBNAME at job $PBS_JOBID"
        exit $errstat
    fi
}

# Guarantee GPUs are visible
#export CUDA_VISIBLE_DEVICES=$(seq 0 $(( $PBS_NGPUS-1 )) | tr  '\r\n' ',')

# Change to working directory - not necessary with #PBS -l wd
cd $PBS_O_WORKDIR

# Terminate the job sequence if the file STOP_SEQUENCE is found in pwd
if [ -f STOP_SEQUENCE ]; then
    echo "STOP_SEQUENCE file found - terminating job sequence $PBS_JOBNAME at job $PBS_JOBID"
    exit 0
fi

#####  START MD WITH A GROMPP  #####

## GROMPP if there's no TPR file (eg, this is the first submission)
if [ ! -f ${PBS_JOBNAME}.tpr ]; then
    $GMX grompp -f ${PBS_JOBNAME}.mdp -c ${PBS_JOBNAME}_start.gro -o ${PBS_JOBNAME}.tpr -p ${PBS_JOBNAME}.top  -n ${PBS_JOBNAME}.ndx -maxwarn 2 || errexit
fi


$GMXMDRUN -v -deffnm ${PBS_JOBNAME} -cpi ${PBS_JOBNAME}.cpt || errexit

#####  CHECK IF JOB IS DONE; IF NOT DONE RESUBMIT THIS SCRIPT  #####


# Check the log file for the number of steps completed
steps_done=$(awk '/Statistics over/ {print $3}' ${PBS_JOBNAME}.log | tail -1)
# Check the mdp file for the number of steps we want
steps_wanted=$(awk '/nsteps *=/ {print $3}' ${PBS_JOBNAME}.mdp | tail -1)
# Resubmit if we need to
if (( steps_done < steps_wanted )); then
	echo "Job ${PBS_JOBID}: ${steps_done}/${steps_wanted} steps completed."
	echo "Resubmitting job sequence..."
	qsub $PBS_JOBNAME
else
	echo "Simulation Complete"
fi
